apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-app
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: phpmyadmin-app
    tier: mysql
  ports:
    - name: phpmyadmin-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-app
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin-app
        tier: mysql
    spec:
      containers:
      - image: phpmyadmin
        name: phpmyadmin-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: phpmyadmin-port
          hostPort: 5000
