apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps-app
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: ftps-app
  ports:
    - name: ftps-data-port
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps-port
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-pass-port
      protocol: TCP
      port: 21000
      targetPort: 21000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - image: 2_ftps_server
        name: ftps-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 20
          name: ftps-data-port
          hostPort: 20
        - containerPort: 21
          name: ftps-port
          hostPort: 21
        - containerPort: 21000
          name: ftps-pass-port
          hostPort: 21000
